FROM sightmachine/simplecv
LABEL maintainer="Srini Karlekar <skarlekar@yahoo.com>"

RUN apt-get update && \
    apt-get install -y python-dev python-pip build-essential && \
    apt-get clean

RUN pip install --index-url https://pypi.python.org/simple/ --upgrade pip
RUN pip install --index-url=https://pypi.python.org/simple/ Flask

WORKDIR /app
COPY app/app.py /app

ENTRYPOINT ["python"]
CMD ["app.py"]
